var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/pages/index.js")
R.c("server/chunks/ssr/_bfc9e6fb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f6324850._.js")
R.c("server/chunks/ssr/[root-of-the-server]__37ef785f._.js")
R.c("server/chunks/ssr/[externals]_next_dist_compiled_@opentelemetry_api_2f2eda7e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__eb0fb79e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__68d47023._.js")
R.c("server/chunks/ssr/[root-of-the-server]__27c26a45._.js")
R.m(647)
module.exports=R.m(647).exports
